import { http } from "@/api";

export type GlobalLeaderSubject = {
  userId: string;
  koreanName: string;
  departmentNames: string[];
  isEvaluationSubject: boolean;
};

export type EvaluateeUser = {
  userId: string;
  koreanName: string;
  departmentNames: string[];
  poolSource: "default" | "extra_pool";
};

export type LeaderReviewGlobalMappingBoard = {
  leaderSubjects: GlobalLeaderSubject[];
  evaluatees: EvaluateeUser[];
  mappings: Array<{
    leaderUserId: string;
    evaluateeUserId: string;
    isAutoGenerated: boolean;
  }>;
};

export const GET_leaderReviewGlobalEvaluateeMappingBoard = async () => {
  const response = await http.get("/leader-review-evaluatee-mapping/global");
  return response.data as { data: LeaderReviewGlobalMappingBoard };
};

export const PUT_leaderReviewGlobalEvaluateeMappings = async (
  links: Array<{ leaderUserId: string; evaluateeUserId: string }>,
) => {
  const response = await http.put("/leader-review-evaluatee-mapping/global", {
    links,
  });
  return response.data as { data: { saved: number } };
};

export const POST_leaderReviewEvaluateeMappingSyncAuto = async () => {
  const response = await http.post(
    "/leader-review-evaluatee-mapping/sync-auto",
  );
  return response.data as { data: { leaders: number }; message?: string };
};

export const PATCH_leaderReviewEvaluationSubject = async (
  userId: string,
  isEvaluationSubject: boolean,
) => {
  const response = await http.patch(
    `/leader-review-evaluatee-mapping/global/subject/${userId}`,
    { isEvaluationSubject },
  );
  return response.data as {
    data: { userId: string; isEvaluationSubject: boolean };
    message?: string;
  };
};

export const POST_leaderReviewEvaluateePoolExtra = async (userId: string) => {
  const response = await http.post(
    "/leader-review-evaluatee-mapping/global/evaluatee-pool",
    { userId },
  );
  return response.data as { data: { userId: string }; message?: string };
};

export const DELETE_leaderReviewEvaluateePoolExtra = async (userId: string) => {
  const response = await http.delete(
    `/leader-review-evaluatee-mapping/global/evaluatee-pool/${userId}`,
  );
  return response.data as { data: { ok: true }; message?: string };
};
