import { http } from "@/api";

export type GlobalLeaderSubject = {
  userId: string;
  koreanName: string;
  departmentNames: string[];
  isEvaluationSubject: boolean;
};

export type EvaluateeUser = {
  userId: string;
  koreanName: string;
  departmentNames: string[];
  poolSource: "default" | "extra_pool";
};

export type LeaderReviewGlobalMappingBoard = {
  leaderSubjects: GlobalLeaderSubject[];
  evaluatees: EvaluateeUser[];
  /** 백엔드: HR 확장 풀(테이블) 기준 userId — 선택 필드 */
  extraPoolUserIds?: string[];
  mappings: Array<{
    leaderUserId: string;
    evaluateeUserId: string;
    isAutoGenerated: boolean;
  }>;
};

/**
 * HTTP 응답 본문에서 추가 후보 풀(extra)에 속한 피평가자 userId를 최대한 수집합니다.
 * (전역 보드 응답 루트 또는 `data` 안에 `extraPoolUserIds` 등이 붙는 경우)
 */
export function collectLeaderReviewExtraPoolUserIdsFromPayload(payload: unknown): string[] {
  const out = new Set<string>();

  const pushString = (v: unknown) => {
    if (typeof v === "string" && v.trim()) {
      out.add(v.trim());
    }
  };

  const consumeArray = (arr: unknown) => {
    if (!Array.isArray(arr)) {
      return;
    }
    for (const item of arr) {
      if (typeof item === "string") {
        pushString(item);
        continue;
      }
      if (item && typeof item === "object" && "userId" in item) {
        pushString((item as { userId?: unknown }).userId);
      }
    }
  };

  const visitObject = (o: Record<string, unknown>) => {
    const keys = [
      "extraPoolUserIds",
      "extraEvaluateeUserIds",
      "extra_pool_user_ids",
      "evaluateePoolExtraUserIds",
      "extraPoolEvaluateeUserIds",
    ] as const;
    for (const k of keys) {
      consumeArray(o[k]);
    }
    const nested = o.extraPool;
    if (nested && typeof nested === "object") {
      consumeArray((nested as { userIds?: unknown }).userIds);
      consumeArray((nested as { evaluateeUserIds?: unknown }).evaluateeUserIds);
    }
    consumeArray(o.evaluateePoolExtras);
    consumeArray(o.evaluatee_pool_extras);
    const list = o.list ?? o.items ?? o.users;
    consumeArray(list);
    consumeArray(o.userIds);
    consumeArray(o.evaluateeUserIds);
  };

  const visit = (node: unknown) => {
    if (!node || typeof node !== "object") {
      return;
    }
    const root = node as Record<string, unknown>;
    visitObject(root);
    const inner = root.data;
    if (inner && typeof inner === "object") {
      visitObject(inner as Record<string, unknown>);
    }
  };

  visit(payload);
  return [...out];
}

export function applyExtraPoolUserIdsToEvaluatees(
  board: LeaderReviewGlobalMappingBoard,
  extraUserIds: ReadonlySet<string>,
): LeaderReviewGlobalMappingBoard {
  if (extraUserIds.size === 0) {
    return board;
  }
  return {
    ...board,
    evaluatees: board.evaluatees.map((e) =>
      extraUserIds.has(e.userId) ? { ...e, poolSource: "extra_pool" as const } : e,
    ),
  };
}

export const GET_leaderReviewGlobalEvaluateeMappingBoard = async () => {
  const response = await http.get("/leader-review-evaluatee-mapping/global");
  return response.data as { data: LeaderReviewGlobalMappingBoard };
};

export const PUT_leaderReviewGlobalEvaluateeMappings = async (
  links: Array<{ leaderUserId: string; evaluateeUserId: string }>,
) => {
  const response = await http.put("/leader-review-evaluatee-mapping/global", {
    links,
  });
  return response.data as { data: { saved: number } };
};

export const POST_leaderReviewEvaluateeMappingSyncAuto = async () => {
  const response = await http.post(
    "/leader-review-evaluatee-mapping/sync-auto",
  );
  return response.data as { data: { leaders: number }; message?: string };
};

export const PATCH_leaderReviewEvaluationSubject = async (
  userId: string,
  isEvaluationSubject: boolean,
) => {
  const response = await http.patch(
    `/leader-review-evaluatee-mapping/global/subject/${userId}`,
    { isEvaluationSubject },
  );
  return response.data as {
    data: { userId: string; isEvaluationSubject: boolean };
    message?: string;
  };
};

export const POST_leaderReviewEvaluateePoolExtra = async (userId: string) => {
  const response = await http.post(
    "/leader-review-evaluatee-mapping/global/evaluatee-pool",
    { userId },
  );
  return response.data as { data: { userId: string }; message?: string };
};

export const DELETE_leaderReviewEvaluateePoolExtra = async (userId: string) => {
  const response = await http.delete(
    `/leader-review-evaluatee-mapping/global/evaluatee-pool/${userId}`,
  );
  return response.data as { data: { ok: true }; message?: string };
};
